// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemadeTiquetess.src.shared.context;

#nullable disable

namespace SistemadeTiquetess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427060140_AddWaitlistAndRescheduling")]
    partial class AddWaitlistAndRescheduling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Aircrafts.infrastructure.Entity.AircraftEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Aircrafts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000030"),
                            Capacity = 180,
                            IsActive = true,
                            Manufacturer = "Airbus",
                            Model = "A320neo",
                            RegistrationNumber = "N123AB"
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Airlines.infrastructure.Entity.AirlineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000010"),
                            Code = "AV",
                            IsActive = true,
                            Name = "Avianca"
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Countries.Infrastructure.Entity.CountryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Code = "CO",
                            IsActive = true,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Code = "US",
                            IsActive = true,
                            Name = "Estados Unidos"
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Customers.Infrastructure.Entity.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000080"),
                            DocumentNumber = "CC-1234567",
                            FullName = "María López",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000081"),
                            DocumentNumber = "CC-7654321",
                            FullName = "Juan Pérez",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.FlightStatus.Infrastructure.Entity.StatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FlightStatuses");
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Flights.Infrastructure.Entity.FlightEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000100"),
                            DepartureDate = new DateTime(2026, 4, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "MIA",
                            FlightNumber = "AV0101",
                            Origin = "BOG",
                            StatusId = new Guid("a1000000-0000-0000-0000-000000000040")
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Reservations.Infrastructure.Entity.RescheduleHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("NewFlightId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PreviousFlightId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("NewFlightId");

                    b.HasIndex("PreviousFlightId");

                    b.HasIndex("ReservationId");

                    b.ToTable("RescheduleHistories");
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Reservations.Infrastructure.Entity.ReservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FlightId");

                    b.HasIndex("StatusId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000140"),
                            CustomerId = new Guid("a1000000-0000-0000-0000-000000000080"),
                            FlightId = new Guid("a1000000-0000-0000-0000-000000000100"),
                            ReservationDate = new DateTime(2026, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = new Guid("a1000000-0000-0000-0000-000000000061")
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Reservations.Infrastructure.Entity.WaitlistEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Waitlists");
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.ReservationsStatus.Infrastructure.Entity.ReservationStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ReservationStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000060"),
                            Name = "Pendiente"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000061"),
                            Name = "Confirmada"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000062"),
                            Name = "Reprogramada"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000063"),
                            Name = "En espera"
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.SeatAvailability.Infrastructure.Entity.SeatAvailabilityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("SeatId");

                    b.ToTable("SeatAvailabilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000130"),
                            FlightId = new Guid("a1000000-0000-0000-0000-000000000100"),
                            IsAvailable = false,
                            SeatId = new Guid("a1000000-0000-0000-0000-000000000120")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000131"),
                            FlightId = new Guid("a1000000-0000-0000-0000-000000000100"),
                            IsAvailable = true,
                            SeatId = new Guid("a1000000-0000-0000-0000-000000000121")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000132"),
                            FlightId = new Guid("a1000000-0000-0000-0000-000000000100"),
                            IsAvailable = true,
                            SeatId = new Guid("a1000000-0000-0000-0000-000000000122")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000133"),
                            FlightId = new Guid("a1000000-0000-0000-0000-000000000100"),
                            IsAvailable = true,
                            SeatId = new Guid("a1000000-0000-0000-0000-000000000123")
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Seats.Infrastructure.Entity.SeatEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000120"),
                            Class = "Economy",
                            Row = "1",
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000121"),
                            Class = "Economy",
                            Row = "1",
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000122"),
                            Class = "Economy",
                            Row = "2",
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000123"),
                            Class = "Economy",
                            Row = "2",
                            SeatNumber = "2B"
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.TicketStatus.Infrastructure.Entity.TicketStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TicketStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000050"),
                            Name = "Emitido"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000051"),
                            Name = "Cancelado"
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Flights.Infrastructure.Entity.FlightEntity", b =>
                {
                    b.HasOne("SistemadeTiquetess.src.modules.FlightStatus.Infrastructure.Entity.StatusEntity", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Reservations.Infrastructure.Entity.RescheduleHistoryEntity", b =>
                {
                    b.HasOne("SistemadeTiquetess.src.modules.Flights.Infrastructure.Entity.FlightEntity", "NewFlight")
                        .WithMany()
                        .HasForeignKey("NewFlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeTiquetess.src.modules.Flights.Infrastructure.Entity.FlightEntity", "PreviousFlight")
                        .WithMany()
                        .HasForeignKey("PreviousFlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeTiquetess.src.modules.Reservations.Infrastructure.Entity.ReservationEntity", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewFlight");

                    b.Navigation("PreviousFlight");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Reservations.Infrastructure.Entity.ReservationEntity", b =>
                {
                    b.HasOne("SistemadeTiquetess.src.modules.Customers.Infrastructure.Entity.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeTiquetess.src.modules.Flights.Infrastructure.Entity.FlightEntity", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeTiquetess.src.modules.ReservationsStatus.Infrastructure.Entity.ReservationStatusEntity", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Flight");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Reservations.Infrastructure.Entity.WaitlistEntity", b =>
                {
                    b.HasOne("SistemadeTiquetess.src.modules.Flights.Infrastructure.Entity.FlightEntity", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeTiquetess.src.modules.Reservations.Infrastructure.Entity.ReservationEntity", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.SeatAvailability.Infrastructure.Entity.SeatAvailabilityEntity", b =>
                {
                    b.HasOne("SistemadeTiquetess.src.modules.Flights.Infrastructure.Entity.FlightEntity", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeTiquetess.src.modules.Seats.Infrastructure.Entity.SeatEntity", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Seat");
                });
#pragma warning restore 612, 618
        }
    }
}
